//Requires restaurant.js so Restaurant objects can be created
var vendingModel = require('./../models/vending.js');

//Creates an array of Restaurants objects with the names, menus, and logos of all our resturants
var machines = [
  new vendingModel.Vending('Atkins','Ground','Room G09','1 Beverage, 2 Snack/Food, 1 Coffee'),
  new vendingModel.Vending('Atkins','1st','Room 134','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Atkins','1st','Room 117','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Atkins','2nd','Room 212C','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Barnhardt Student Activity Center','Ground','Room 054 (Loading Dock)','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Barnhardt Student Activity Center','1st','Room 103 (Atrium)','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Barnhardt Student Activity Center','3rd','Room 346','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Barnhardt Student Activity Center','1st','Room 132','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Belk Gymnasium','1st Floor','1st Floor','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Bioinformatics','1st','Room 114','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Burson','1st','Room 120','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Burson','2nd','Room 201','1 Beverage'),
  new vendingModel.Vending('Cameron Hall','Lobby','Room 101','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Cone University Center','2nd','Room 243A','2 Beverage, 1 Snack/Food, 1 Coffee'),
  new vendingModel.Vending('College of Health and Human Services','2nd','Room 293','1 Beverage, 1 Snack'),
  new vendingModel.Vending('College of Health and Human Services','1st','Room 125A','2 Beverage, 1 Snack'),
  new vendingModel.Vending('College of Education','1st','Room 109','3 Beverage, 1 Snack'),
  new vendingModel.Vending('Colvard','1st','Room 1000','2 Beverage'),
  new vendingModel.Vending('Colvard','2nd','Room 2006','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Colvard','5th','Room 5049','2 Beverage, 1 Snack'),
  new vendingModel.Vending('CRI Deck 1','1st','Level 1','1 Beverage'),
  new vendingModel.Vending('CRI Deck 1','4th','Level 4','1 Beverage'),
  new vendingModel.Vending('Denny','2nd','Room 220C','2 Beverage, 2 Snack'),
  new vendingModel.Vending('Duke Centennial Hall','2nd','Room 235B','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Duke Centennial Hall','3rd','Room 336B','1 Beverage'),
  new vendingModel.Vending('East Deck 2','1st','Outside','2 Beverage'),
  new vendingModel.Vending('EPIC Building','2nd','Room 2311','1 Beverage, 1 Snack'),
  new vendingModel.Vending('EPIC Building','3rd','Room 3311','1 Beverage, 1 Snack'),
  new vendingModel.Vending('EPIC Building','1st','Room 1209','1 Beverage, 1 Snack'),
  new vendingModel.Vending('EPIC Building','Ground','Room G210','2 Beverage, 1 Snack'),
  new vendingModel.Vending('EPIC Building','2nd','Room 2209','1 Beverage, 1 Snack'),
  new vendingModel.Vending('EPIC Building','3rd','Room 3209','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Facilities Annex One (J-Building)','1st','Automotive','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Facilities Ops and Parking (FOPS)','1st','Room 124E','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Facilities Management & Police & Public Safety','2nd','Room 246','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Facilities Management & Police & Public Safety','1st','Room 168','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Fretwell','1st','Room 100','4 Beverage, 1 Snack'),
  new vendingModel.Vending('Fretwell','1st','Room 118','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Fretwell','1st','Room 128','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Friday','1st','Room 129','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Grigg Hall','2nd','Room 242','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Halton-Wagner Tennis Complex','2nd','Room 202','1 Beverage'),
  new vendingModel.Vending('Hickory','1st','1st Floor','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Housing and Residence Life','1st','Room 018','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Judy W. Rose Football Center','Lower Level','Lower Level (Near Training Room)','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Kennedy','1st','Room 108','1 Beverage, 1 Snack'),
  new vendingModel.Vending('King','1st','Room 005','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Lot 14','Ground','Outside','1 Beverage'),
  new vendingModel.Vending('Martin Hall','1st','Vending Room','2 Beverage, 1 Snack, 1 Frozen Foods'),
  new vendingModel.Vending('McEniry','1st','Room 104','3 Beverage, 1 Snack'),
  new vendingModel.Vending('Popp Martin Student Union','1st','Room 150 (Norms)','1 Beverage'),
  new vendingModel.Vending('Popp Martin Student Union','Lower Level','Room 013','1 Beverage, 1 Snack'),
  new vendingModel.Vending('PORTAL','2nd','Room 203 (Break Room)','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Price Counseling Center','1st','Room 145','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Prospector','Lobby','Room 111C','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Reese','4th','Room 424','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Robinson','1st','Room 101','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Rowe','1st','Room 122 (By Elevator)','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Smith','3rd','300A','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Storrs','1st','Room 186','2 Beverage, 1 Snack'),
  new vendingModel.Vending('Student Health Center','1st','Across From Room 101','1 Beverage, 1 Snack'),
  new vendingModel.Vending('Union Deck','Ground','Outside','1 Beverage'),
  new vendingModel.Vending('University Recreation Center','1st','Near elevators','2 Beverage, 1 Snack, 1 Vengo'),
  new vendingModel.Vending('West Deck','3rd','Level 3','1 Beverage'),
  new vendingModel.Vending('Woodward Hall','1st','Room 112','2 Beverage, 2 Snack'),
];

//returns the array of restaurants
function getMachines(){
  return machines;
}

module.exports.getMachines = getMachines;
